import type { Metadata } from 'next'
import './globals.css'
import { Footer, Header } from '@/widgets/layout'
import { notoSansKr } from '@/lib/font'

export const metadata: Metadata = {
    title: 'Eunsu Resume',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${notoSansKr.className} antialiased`}>
                <div className='min-h-screen bg-white'>
                    <div className='max-w-screen-xl mx-auto'>{children}</div>
                    <Footer />
                </div>
            </body>
        </html>
    )
}
